### PR TITLE
Port the README file to Markdown to ease readability and fix typos

### PR DESCRIPTION
**Pull request by ITAYC0HEN**
This pull request ports the README file of the project to Markdown. I think it will be easier to read and access it through GitHub when it shows in Markdown.

Thanks for the project!

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Seems like this PR was merged directly :)
If this is the case, I think the PR can be closed.

**Comment by vitaly-kamluk** [comment]
Hi,
I have merged and extended your changes. As we replaced default branch from 18.04 to 20.04 in the meantime, this pull request hasn't been autoclosed by Github. Closing this manually now.

**Comment by ITAYC0HEN** [comment]
Good work, Vitali :)

**Comment by ITAYC0HEN** [comment]
Good work, Vitaly :)

**Pull request closed without merging**
